### ISSUE TITLE
Jenkins Docker/Kubernetes DNS resolution to proxy with random name

### ISSUE THREAD

**Issue by sblatnick** [dependabot/cli#159]
I'm trying to run dependabot within a Jenkins pipeline running on linux nodes in a docker-in-docker ([dind](https://hub.docker.com/_/docker)) container.  During the build, I see these errors:
```
updater | 2023/07/31 19:31:33 INFO Checking all dependencies for version updates...
updater | 2023/07/31 19:31:33 INFO Checking if javax.servlet:javax.servlet-api 4.0.1 needs updating
  proxy | 2023/07/31 19:31:33 [002] 200 http://host.docker.internal:8088/update_jobs/cli/increment_metric
  proxy | 2023/07/31 19:41:43 [003] POST http://host.docker.internal:8088/update_jobs/cli/record_update_job_error
{"data":{"error-type":"unknown_error","error-details":null},"type":"record_update_job_error"}
  proxy | 2023/07/31 19:41:43 [003] 200 http://host.docker.internal:8088/update_jobs/cli/record_update_job_error
updater | 2023/07/31 19:41:43 ERROR Error processing javax.servlet:javax.servlet-api (Excon::Error::Socket)
updater | 2023/07/31 19:41:43 ERROR no address for angry_kare6 (Resolv::ResolvError)
updater | 2023/07/31 19:41:43 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/excon-0.99.0/lib/excon/socket.rb:170:in `connect'
...
updater | 2023/07/31 19:41:43 ERROR /home/dependabot/common/lib/dependabot/registry_client.rb:18:in `get'
updater | 2023/07/31 19:41:43 ERROR /home/dependabot/maven/lib/dependabot/maven/update_checker/version_finder.rb:164:in `fetch_dependency_metadata'
```
I noticed these lines in proxy.go:
```
	hostName := namesgenerator.GetRandomName(1)
	proxyContainer, err := cli.ContainerCreate(ctx, config, hostCfg, nil, nil, hostName)
```

I think the problem is that docker sets up a container with a generated random name, in this case "angry_kare6", and then kubernetes addresses the pod using something like "angry_kare6.jenkins.svc.cluster.local".

Is there any way for me to add the short hostname for pods in the same namespace to the hostname resolution?

Apologies if I've missed any obvious solution.

**Comment by mctofu** [comment]
In the Dependabot action, we worked around this issue by configuring the proxy via ip address instead of hostname: https://github.com/github/dependabot-action/pull/136

**Comment by sblatnick** [comment]
Thanks @mctofu that looks useful.  I don't see any way for me as a consumer of dependabot/cli to fix that, so I suspect I will need someone like @jakecoffman to change the logic.

**Comment by jakecoffman** [comment]
@sblatnick do you want to test with the latest CLI version just released and see if it fixed it?

**Comment by sblatnick** [comment]
Now I get a missing shared library error:
`[Pipeline] sh
+ ./dependabot update -f job.yaml --local ./ -o dependabot-results.yaml
Error loading shared library libresolv.so.2: No such file or directory (needed by ./dependabot)
Error relocating ./dependabot: __res_search: symbol not found`

I'm using a provided image, so it looks like I may need to make my own?  I'll start working on that unless you have an alternative.

**Comment by jakecoffman** [comment]
Sounds like https://github.com/golang/go/issues/59304

I guess we'll need to add build flags to make it a fully statically linked binary again.

**Comment by sblatnick** [comment]
Preliminary testing seems to show this command adds the proper dependency:
```
apk add gcompat --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main
```
I am working on using a new image with that package, and I'll let you know if it ends up working.

**Comment by sblatnick** [comment]
Great news!  This seems package combined with your changes seem to have fixed this issue.
