### ISSUE TITLE
Connection timeout when contacting host.docker.internal

### ISSUE THREAD

**Issue by l0b0** [dependabot/cli#192]
Full logs:

```
❯ steam-run ~/download/dependabot-v1.39.0-linux-amd64/dependabot update github_actions orgname/reponame --local my\ projects/reponame/
    cli | 2023/11/07 22:35:08 Adding missing credentials-metadata into job definition
    cli | 2023/11/07 22:35:08 using image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest at sha256:ce6fc9c3d663d090303dd639d7025fe12fdcb63f36b4a4d3c346af87afe696f7
    cli | 2023/11/07 22:35:08 using image ghcr.io/dependabot/dependabot-updater-github-actions at sha256:9d15b67733b5994be93e6a30a2669d25793de013e2091c254b797b34436f6d9b
  proxy | 2023/11/07 22:35:09 proxy starting, commit: 720801aa060f51bd9dc8b5753a6045ec3d7f5321
  proxy | 2023/11/07 22:35:09 initializing metrics client: No address passed and autodetection from environment failed
  proxy | 2023/11/07 22:35:09 GitHubAPIHandler has no app access tokens
  proxy | 2023/11/07 22:35:09 Listening (:1080)
updater | Reinitialized existing Git repository in /home/dependabot/dependabot-updater/repo/.git/
updater | Updating certificates in /etc/ssl/certs...
updater | rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
updater | 1 added, 0 removed; done.
updater | Running hooks in /etc/ca-certificates/update.d...
updater | done.
updater | 2023/11/07 22:35:14 INFO Raven 3.1.2 configured not to capture errors: DSN not set
updater | 2023/11/07 22:35:14 INFO Starting job processing
updater | 2023/11/07 22:35:14 INFO Finished job processing
updater | 2023/11/07 22:35:15 INFO Raven 3.1.2 configured not to capture errors: DSN not set
updater | 2023/11/07 22:35:15 INFO Starting job processing
  proxy | 2023/11/07 22:35:15 [002] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 22:35:15 [002] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 22:35:16 [004] GET https://github.com:443/actions/setup-node.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 22:35:16 [004] 200 https://github.com:443/actions/setup-node.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 22:35:16 [006] GET https://github.com:443/aws-actions/configure-aws-credentials.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 22:35:17 [006] 200 https://github.com:443/aws-actions/configure-aws-credentials.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 22:35:17 [008] GET https://github.com:443/linz/action-pull-request-lint.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 22:35:18 [008] 200 https://github.com:443/linz/action-pull-request-lint.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 22:35:18 [009] POST http://host.docker.internal:33761/update_jobs/cli/update_dependency_list
updater | 2023/11/07 22:37:28 ERROR dial tcp 172.17.0.1:33761: connect: connection timed out
updater | 
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/lib/dependabot/api_client.rb:151:in `update_dependency_list'
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/lib/dependabot/service.rb:82:in `update_dependency_list'
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:29:in `perform_job'
updater | 2023/11/07 22:37:28 ERROR /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/07 22:37:28 ERROR bin/update_files.rb:24:in `<main>'
  proxy | 2023/11/07 22:37:28 [009] No response from server
  proxy | 2023/11/07 22:37:28 [009] No response from server
  proxy | 2023/11/07 22:37:28 [010] POST http://host.docker.internal:33761/update_jobs/cli/record_update_job_error
```

I also tried [building the CLI for NixOS](https://github.com/NixOS/nixpkgs/pull/266171), but ended up with what looks like the same problem (after `cd`-ing into the relevant repo):

```
❯ dependabot update github_actions orgname/reponame --local .
    cli | 2023/11/08 02:06:35 Adding missing credentials-metadata into job definition
    cli | 2023/11/08 02:06:35 pulling image: ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest
    cli | 2023/11/08 02:06:39 using image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest at sha256:ce6fc9c3d663d090303dd639d7025fe12fdcb63f36b4a4d3c346af87afe696f7
    cli | 2023/11/08 02:06:39 pulling image: ghcr.io/dependabot/dependabot-updater-github-actions
    cli | 2023/11/08 02:07:22 using image ghcr.io/dependabot/dependabot-updater-github-actions at sha256:7157f8a8b4e3fa0f2d3273685728674fa9ae3a2d0ddc0c31c8d58008f6a8dda7
  proxy | 2023/11/08 02:07:24 proxy starting, commit: 720801aa060f51bd9dc8b5753a6045ec3d7f5321
  proxy | 2023/11/08 02:07:24 initializing metrics client: No address passed and autodetection from environment failed
  proxy | 2023/11/08 02:07:24 GitHubAPIHandler has no app access tokens
  proxy | 2023/11/08 02:07:24 Listening (:1080)
updater | Reinitialized existing Git repository in /home/dependabot/dependabot-updater/repo/.git/
updater | Updating certificates in /etc/ssl/certs...
updater | rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
updater | 1 added, 0 removed; done.
updater | Running hooks in /etc/ca-certificates/update.d...
updater | done.
updater | 2023/11/08 02:07:29 INFO Raven 3.1.2 configured not to capture errors: DSN not set
updater | 2023/11/08 02:07:29 INFO Starting job processing
updater | 2023/11/08 02:07:29 INFO Finished job processing
updater | 2023/11/08 02:07:30 INFO Raven 3.1.2 configured not to capture errors: DSN not set
updater | 2023/11/08 02:07:30 INFO Starting job processing
  proxy | 2023/11/08 02:07:30 [002] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 02:07:31 [002] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 02:07:31 [004] GET https://github.com:443/actions/setup-node.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 02:07:31 [004] 200 https://github.com:443/actions/setup-node.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 02:07:32 [006] GET https://github.com:443/aws-actions/configure-aws-credentials.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 02:07:32 [006] 200 https://github.com:443/aws-actions/configure-aws-credentials.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 02:07:32 [008] GET https://github.com:443/linz/action-pull-request-lint.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 02:07:33 [008] 200 https://github.com:443/linz/action-pull-request-lint.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 02:07:33 [009] POST http://host.docker.internal:38303/update_jobs/cli/update_dependency_list
updater | 2023/11/08 02:09:43 ERROR dial tcp 172.17.0.1:38303: connect: connection timed out
updater | 
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/lib/dependabot/api_client.rb:151:in `update_dependency_list'
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/lib/dependabot/service.rb:82:in `update_dependency_list'
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:29:in `perform_job'
updater | 2023/11/08 02:09:43 ERROR /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/08 02:09:43 ERROR bin/update_files.rb:24:in `<main>'
  proxy | 2023/11/08 02:09:43 [009] No response from server
  proxy | 2023/11/08 02:09:43 [009] No response from server
  proxy | 2023/11/08 02:09:43 [010] POST http://host.docker.internal:38303/update_jobs/cli/record_update_job_error
updater | 2023/11/08 02:11:54 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------+
updater | |    Errors     |
updater | +---------------+
updater | | unknown_error |
updater | +---------------+
  proxy | 2023/11/08 02:11:54 [010] No response from server
  proxy | 2023/11/08 02:11:54 [010] No response from server
  proxy | 2023/11/08 02:11:55 0/4 calls cached (0%)
```

The above were both using Docker "root-ful" mode. I tried configuring rootless mode instead, and now the connection is instead refused immediately:

```
❯ dependabot update github_actions orgname/reponame --local .
    cli | 2023/11/08 04:05:46 Adding missing credentials-metadata into job definition
    cli | 2023/11/08 04:05:46 pulling image: ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest
    cli | 2023/11/08 04:05:50 using image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:latest at sha256:ce6fc9c3d663d090303dd639d7025fe12fdcb63f36b4a4d3c346af87afe696f7
    cli | 2023/11/08 04:05:50 pulling image: ghcr.io/dependabot/dependabot-updater-github-actions
    cli | 2023/11/08 04:06:22 using image ghcr.io/dependabot/dependabot-updater-github-actions at sha256:7157f8a8b4e3fa0f2d3273685728674fa9ae3a2d0ddc0c31c8d58008f6a8dda7
  proxy | 2023/11/08 04:06:22 proxy starting, commit: 720801aa060f51bd9dc8b5753a6045ec3d7f5321
  proxy | 2023/11/08 04:06:22 initializing metrics client: No address passed and autodetection from environment failed
  proxy | 2023/11/08 04:06:22 GitHubAPIHandler has no app access tokens
  proxy | 2023/11/08 04:06:22 Listening (:1080)
updater | Reinitialized existing Git repository in /home/dependabot/dependabot-updater/repo/.git/
updater | Updating certificates in /etc/ssl/certs...
updater | rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
updater | 1 added, 0 removed; done.
updater | Running hooks in /etc/ca-certificates/update.d...
updater | done.
updater | 2023/11/08 04:06:27 INFO Raven 3.1.2 configured not to capture errors: DSN not set
updater | 2023/11/08 04:06:27 INFO Starting job processing
updater | 2023/11/08 04:06:27 INFO Finished job processing
updater | 2023/11/08 04:06:28 INFO Raven 3.1.2 configured not to capture errors: DSN not set
updater | 2023/11/08 04:06:28 INFO Starting job processing
  proxy | 2023/11/08 04:06:28 [002] GET https://github.com:443/linz/action-pull-request-lint.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:29 [002] 200 https://github.com:443/linz/action-pull-request-lint.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:29 [004] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:29 [004] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:29 [006] GET https://github.com:443/actions/setup-node.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:30 [006] 200 https://github.com:443/actions/setup-node.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:30 [008] GET https://github.com:443/azure/setup-kubectl.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:30 [008] 200 https://github.com:443/azure/setup-kubectl.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:30 [010] GET https://github.com:443/aws-actions/configure-aws-credentials.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:31 [010] 200 https://github.com:443/aws-actions/configure-aws-credentials.git/info/refs?service=git-upload-pack
  proxy | 2023/11/08 04:06:31 [011] POST http://host.docker.internal:44117/update_jobs/cli/update_dependency_list
  proxy | 2023/11/08 04:06:31 [011] No response from server
  proxy | 2023/11/08 04:06:31 [011] No response from server
updater | 2023/11/08 04:06:31 ERROR dial tcp 172.17.0.1:44117: connect: connection refused
updater | 
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/lib/dependabot/api_client.rb:151:in `update_dependency_list'
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/lib/dependabot/service.rb:82:in `update_dependency_list'
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:29:in `perform_job'
updater | 2023/11/08 04:06:31 ERROR /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/08 04:06:31 ERROR bin/update_files.rb:24:in `<main>'
  proxy | 2023/11/08 04:06:31 [012] POST http://host.docker.internal:44117/update_jobs/cli/record_update_job_error
  proxy | 2023/11/08 04:06:31 [012] No response from server
  proxy | 2023/11/08 04:06:31 [012] No response from server
updater | 2023/11/08 04:06:31 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------+
updater | |    Errors     |
updater | +---------------+
updater | | unknown_error |
updater | +---------------+
  proxy | 2023/11/08 04:06:33 0/5 calls cached (0%)
```

**Comment by l0b0** [comment]
Ping? It'd be great to know whether I'm not using the CLI correctly, or Docker isn't set up the way it expects, or what. I also tried `docker network prune`, but that didn't seem to make any difference.

**Comment by asininemonkey** [comment]
In my case it's a NixOS firewall issue as disabling it before running `dependabot` works for me. Not sure what the long term solution should be.

**Comment by asininemonkey** [comment]
The following resolved the issue for me on NixOS allowing the firewall to be re-enabled and `dependabot` to run successfully:

`networking.firewall.trustedInterfaces = [ "docker0" ];`

**Comment by l0b0** [comment]
> The following resolved the issue for me on NixOS allowing the firewall to be re-enabled and `dependabot` to run successfully:
> 
> `networking.firewall.trustedInterfaces = [ "docker0" ];`

Is there some way to do this specifically for the Dependabot containers, or to limit it to a single command? Because I don't want to trust *every* Docker container I run that much.

**Comment by asininemonkey** [comment]
Not sure. Possibly create another Docker network to run Dependabot in and see if that exposes an interface that can be trusted in your firewall.

In my situation I have no other containers running that I care about so the above solution works for me.

It should be noted that incoming connections to `docker0` remain firewalled if that's your concern.

**Comment by l0b0** [comment]
> It should be noted that incoming connections to `docker0` remain firewalled if that's your concern.

No, it's more that I would like to minimise the impact from any badly implemented or malicious containers, in case I ever happen to run one. I've already set Docker to be root-less, to avoid most of that craziness.

**Comment by asininemonkey** [comment]
Understood. Additional firewalled Docker network/interface may be the only solution then.

**Comment by l0b0** [comment]
Closing since this seems to be a firewall issue.
